2020-05-07 10:23:49.751918: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-05-07 10:23:49.757864: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2020-05-07 10:23:49.758082: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56144c4923e0 executing computations on platform Host. Devices:
2020-05-07 10:23:49.758143: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
/users/PAS1585/llavez99/work/nbody/nBodyNN/training/test.py:45: FutureWarning:

Method .as_matrix will be removed in a future version. Use .values instead.

/users/PAS1585/llavez99/work/nbody/nBodyNN/training/test.py:46: FutureWarning:

Method .as_matrix will be removed in a future version. Use .values instead.

   finalFile  ...      dyf3
0          1  ... -0.100621
1          1  ... -0.101038
2          1  ... -0.101454
3          1  ... -0.101870
4          1  ... -0.102286

[5 rows x 30 columns]
(1147503, 16) (1147503, 12)
(286876, 16) (286876, 12)
Traceback (most recent call last):
  File "/users/PAS1585/llavez99/work/nbody/nBodyNN/training/test.py", line 63, in <module>
    network.save_weights(workDir + 'weights/model_init_test.h5')
  File "/users/PAS1585/llavez99/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 449, in save_wrapper
    save_function(obj, filepath, overwrite, *args, **kwargs)
  File "/users/PAS1585/llavez99/.local/lib/python3.6/site-packages/keras/engine/network.py", line 1183, in save_weights
    with h5py.File(filepath, 'w') as f:
  File "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/h5py/_hl/files.py", line 148, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/users/PAS1585/llavez99/work/nbody/nBodyNN/training/weights/model_init_test.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
